version: '3.8'

services:
  # Redis for L2 caching
  redis:
    image: redis:7-alpine
    container_name: employment-act-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Employment Act API
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: employment-act-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-8001}:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - VLLM_URL=${VLLM_URL:-http://host.docker.internal:8000}
      - REDIS_URL=redis://redis:6379
      - WORKERS=3
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: employment-act-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      api:
        condition: service_healthy
    profiles:
      - nginx

volumes:
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  default:
    name: employment-act-network