name: faiss-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - faiss-cpu=1.9.0
  - rank-bm25
  - sentence-transformers
  - pandas
  - tqdm
  - numpy=1.26.4
  - pip
  - pip:
    - transformers>=4.43
    - accelerate
    - peft
    - trl
    - datasets
    - fastapi
    - uvicorn
    - pydantic
    - python-dotenv
    - streamlit
    - vllm
    - PyMuPDF