name: ea
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python + numeric stack
  - python=3.12
  - numpy=1.26.4           # FAISS 1.9.x requires NumPy < 2
  - pandas
  - tqdm

  # Vector search + retrieval
  - faiss-cpu=1.9.0
  - rank-bm25

  # YAML/config
  - pyyaml

  # PyTorch with CUDA 12.1 (uses NVIDIA channel runtime/libs)
  - pytorch
  - torchvision
  - pytorch-cuda=12.1

  # Optional: classic ML utils
  - scikit-learn

  # Pip extras
  - pip
  - pip:
      # HF + training
      - "sentence-transformers>=3.0.0"
      - transformers>=4.43
      - accelerate
      - peft
      - trl
      - datasets
      - bitsandbytes
      - sentencepiece
      - matplotlib

      # API / server
      - fastapi
      - uvicorn[standard]
      - gunicorn
      - httpx
      - backoff
      - redis
      - python-dotenv

      # UI / tools / inference
      - streamlit
      - vllm
      - pymupdf       # aka PyMuPDF
