name: ea
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python + numeric stack
  - python=3.12
  - numpy=1.26.4           # FAISS 1.9.x requires NumPy < 2
  - pandas
  - tqdm
  - scipy=1.11.*           # Compatible with NumPy 1.26.x on Py3.12

  # Vector search + retrieval
  - faiss-cpu=1.9.0
  - rank-bm25

  # YAML/config
  - pyyaml

  # PyTorch with CUDA 12.1 (uses NVIDIA channel runtime/libs)
  - pytorch
  - pytorch-cuda=12.1

  # Optional: classic ML utils
  - scikit-learn

  # Pip extras
  - pip
  - pip:
      # HF + training
      - "sentence-transformers>=3.0.0"
      - transformers>=4.43
      - accelerate
      - peft
      - trl
      - datasets
      - bitsandbytes
      - sentencepiece
      - matplotlib

      # API / server (pins compatible with vLLM 0.5.5 shutdown path)
      - "fastapi==0.111.*"
      - "uvicorn[standard]==0.29.*"
      - "starlette==0.37.2"
      - gunicorn
      - httpx
      - backoff
      - redis
      - python-dotenv

      # UI / tools / inference
      - streamlit
      - pymupdf       # aka PyMuPDF
      # Note: vLLM is large; install only if needed
      # - "vllm==0.5.*"

      # Optional: torchvision (if you truly need it); prefer Python 3.11
      # - torchvision

      # Optional: FlashAttention 2 (L4/Ampere+). Prefer SDPA if install fails.
      # - flash-attn  # may require --no-build-isolation and matching Torch/CUDA
